

name: Java Maven Build & Publish Artifact

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest                    # Define 'Runner/worker machine' where this job needs to execute

    steps:
    - uses: actions/checkout@v3              # To checkout the GitHub repo for the workflow to run
    - name: Set up JDK 17
      uses: actions/setup-java@v3             # Setting up JDK
      with:
        java-version: '17'                   # Setting Java version and distribution in next line 
        distribution: 'temurin'
        cache: maven                         # Cache Maven dependencies to avoid repeated downloads.
    - name: Build with Maven
      run: mvn -B package --file pom.xml      # Building Java project with Maven 

   
  publish-job:
    runs-on: ubuntu-latest
    needs: build_test                       # To set condition Run this stage only if ‘build_test’ succeeds.
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mvn --batch-mode --update-snapshots verify   # To execute maven verify goal against Test cases for 'junit' testing
    - run: mkdir staging && cp target/*.jar staging     # Creating a new directory 'staging' & moving artifact to new directory
    - uses: actions/upload-artifact@v3                  # Create a zip file 'Package_artifact' & move artifacts in it for download
      with:
        name: Package_artifact
        path: staging